application: make-an-app-yay
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css/
  static_dir: Frontend/css

- url: /images/
  static_dir: Frontend/images

- url: /js/
  static_dir: Frontend/js/

- url: /.*
  script: server.app

libraries:
- name: jinja2
  version: latest

